#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-taxize
Version  : 0.9.6
Release  : 8
URL      : https://cran.r-project.org/src/contrib/taxize_0.9.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/taxize_0.9.6.tar.gz
Summary  : Taxonomic Information from Around the Web
Group    : Development/Tools
License  : MIT
Requires: R-ape
Requires: R-bold
Requires: R-crul
Requires: R-natserv
Requires: R-reshape2
Requires: R-ritis
Requires: R-rotl
Requires: R-rredlist
Requires: R-vegan
Requires: R-wikitaxa
Requires: R-worrms
Requires: R-zoo
BuildRequires : R-ape
BuildRequires : R-bold
BuildRequires : R-crul
BuildRequires : R-natserv
BuildRequires : R-reshape2
BuildRequires : R-ritis
BuildRequires : R-rotl
BuildRequires : R-rredlist
BuildRequires : R-vegan
BuildRequires : R-wikitaxa
BuildRequires : R-worrms
BuildRequires : R-zoo
BuildRequires : buildreq-R

%description
taxize
======
[![cran checks](https://cranchecks.info/badges/worst/taxize)](https://cranchecks.info/pkgs/taxize)
[![Build Status](https://travis-ci.org/ropensci/taxize.svg?branch=master)](https://travis-ci.org/ropensci/taxize)
[![Build status](https://ci.appveyor.com/api/projects/status/6mgc02mkd8j4sq3g/branch/master)](https://ci.appveyor.com/project/sckott/taxize-175/branch/master)
[![codecov.io](https://codecov.io/github/ropensci/taxize/coverage.svg?branch=master)](https://codecov.io/github/ropensci/taxize?branch=master)
[![rstudio mirror downloads](http://cranlogs.r-pkg.org/badges/taxize)](https://github.com/metacran/cranlogs.app)
[![cran version](http://www.r-pkg.org/badges/version/taxize)](https://cran.r-project.org/package=taxize)

%prep
%setup -q -c -n taxize

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551070886

%install
export SOURCE_DATE_EPOCH=1551070886
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library taxize
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library taxize
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library taxize
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library taxize|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/taxize/CITATION
/usr/lib64/R/library/taxize/DESCRIPTION
/usr/lib64/R/library/taxize/INDEX
/usr/lib64/R/library/taxize/LICENSE
/usr/lib64/R/library/taxize/Meta/Rd.rds
/usr/lib64/R/library/taxize/Meta/data.rds
/usr/lib64/R/library/taxize/Meta/features.rds
/usr/lib64/R/library/taxize/Meta/hsearch.rds
/usr/lib64/R/library/taxize/Meta/links.rds
/usr/lib64/R/library/taxize/Meta/nsInfo.rds
/usr/lib64/R/library/taxize/Meta/package.rds
/usr/lib64/R/library/taxize/Meta/vignette.rds
/usr/lib64/R/library/taxize/NAMESPACE
/usr/lib64/R/library/taxize/NEWS.md
/usr/lib64/R/library/taxize/R/taxize
/usr/lib64/R/library/taxize/R/taxize.rdb
/usr/lib64/R/library/taxize/R/taxize.rdx
/usr/lib64/R/library/taxize/data/Rdata.rdb
/usr/lib64/R/library/taxize/data/Rdata.rds
/usr/lib64/R/library/taxize/data/Rdata.rdx
/usr/lib64/R/library/taxize/doc/index.html
/usr/lib64/R/library/taxize/doc/name_cleaning.Rmd
/usr/lib64/R/library/taxize/doc/name_cleaning.html
/usr/lib64/R/library/taxize/doc/taxize_case_study.Rmd
/usr/lib64/R/library/taxize/doc/taxize_case_study.html
/usr/lib64/R/library/taxize/doc/taxize_infotable.Rmd
/usr/lib64/R/library/taxize/doc/taxize_infotable.html
/usr/lib64/R/library/taxize/doc/taxize_vignette.Rmd
/usr/lib64/R/library/taxize/doc/taxize_vignette.html
/usr/lib64/R/library/taxize/examples/species.txt
/usr/lib64/R/library/taxize/help/AnIndex
/usr/lib64/R/library/taxize/help/aliases.rds
/usr/lib64/R/library/taxize/help/paths.rds
/usr/lib64/R/library/taxize/help/taxize.rdb
/usr/lib64/R/library/taxize/help/taxize.rdx
/usr/lib64/R/library/taxize/html/00Index.html
/usr/lib64/R/library/taxize/html/R.css
/usr/lib64/R/library/taxize/ignore/aou_notes.R
/usr/lib64/R/library/taxize/ignore/nature_serve.R
/usr/lib64/R/library/taxize/ignore/phylomatic_tree2.R
/usr/lib64/R/library/taxize/ignore/phytools_fxns_touse.r
/usr/lib64/R/library/taxize/ignore/rank_ref_script.R
/usr/lib64/R/library/taxize/ignore/rbladj.r
/usr/lib64/R/library/taxize/ignore/taxonclass.R
/usr/lib64/R/library/taxize/ignore/taxonclass2.R
/usr/lib64/R/library/taxize/ignore/taxonid.R
/usr/lib64/R/library/taxize/ignore/tests/test-ubio_classification.R
/usr/lib64/R/library/taxize/ignore/tests/test-ubio_id.R
/usr/lib64/R/library/taxize/ignore/tests/test-ubio_namebank.R
/usr/lib64/R/library/taxize/ignore/tests/test-ubio_search.R
/usr/lib64/R/library/taxize/ignore/tests/test-ubio_synonyms.R
/usr/lib64/R/library/taxize/ignore/try_with_timeout.R
/usr/lib64/R/library/taxize/vign/cache/__packages
/usr/lib64/R/library/taxize/vign/cache/taxname_0f3fcc7119f159af267de7a029f64f5e.RData
/usr/lib64/R/library/taxize/vign/cache/taxname_0f3fcc7119f159af267de7a029f64f5e.rdb
/usr/lib64/R/library/taxize/vign/cache/taxname_0f3fcc7119f159af267de7a029f64f5e.rdx
/usr/lib64/R/library/taxize/vign/cache/tnrs_c39c1e0c556437f6b37ba3c369e8be54.RData
/usr/lib64/R/library/taxize/vign/cache/tnrs_c39c1e0c556437f6b37ba3c369e8be54.rdb
/usr/lib64/R/library/taxize/vign/cache/tnrs_c39c1e0c556437f6b37ba3c369e8be54.rdx
/usr/lib64/R/library/taxize/vign/name_cleaning.Rmd
/usr/lib64/R/library/taxize/vign/name_cleaning.md
/usr/lib64/R/library/taxize/vign/taxize_case_study.Rmd
/usr/lib64/R/library/taxize/vign/taxize_case_study.md
/usr/lib64/R/library/taxize/vign/taxize_infotable.Rmd
/usr/lib64/R/library/taxize/vign/taxize_infotable.md
/usr/lib64/R/library/taxize/vign/taxize_vignette.Rmd
/usr/lib64/R/library/taxize/vign/taxize_vignette.md
